os: linux
language: node_js
node_js:
- '12'
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: RMdlba1l+qY8NIFw6Zt9OFE2ks2cY9XIUL1n2goSn/byFZtkZ8Midtbb1k4uc+a5rHK14BTxQ0slnZYxDoYBdI8Y82u0VwQq+kXU12UFqkWrCaMSY8YQhEfFL4c+Kbm8z5wwe8QiVnvd6WICP1eej+7LlXy4ubhW9M0UYnO6v1JwFtxtqRaUXNYfU6+CSgs8SMJOBQdUQNG8EIdsfRkIJr+kteDt2/tc0R9TYTKJW9pUU8H/iSJvg8rfvfCzW8/R0mToMmXLT0MuN2Ju2Wx13TNwzqlRX2n8SHsM5RLDBjm6Q6h7A6gybJ4Kju+KhPqvtyGAi/qdE94AyGlCVT/O5v0jOYFB5o3R98jr/C0y7Tj2/X4/1+x3MvAreZOZA4EIGS4wVxXWAdYHMDP6o35JXJqR3X7i9YhN9maXyZRHdsV8VFjeifUUejaWoJ19Jh1ag+77qpEJF5PbVkzchKKtLrMt3qVo+TknzCXltGeuKSLLS/KJO4PB4ERCaAR0wt+wdZy3gZK1/Pybt08QyV+pqu3DCO7UBsHX7zO1jSMxujzNdQqhkK1HGcQ/dXSBUZj7WI8zh+J2c+LhIWd0Zd6Cl+Jlcaq7Ci321HWlVnP2xogFqJsbWmQt99D/RNZrNqsGox94Y6xJLAzMsZ1qf5GSDu+ICUiJ0V6JxTMnLsyk2EI=
  app: corvo-astral
  on:
    branch: master
