os: linux
language: node_js
node_js:
- '12'
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: dx6wU8ZJpeP03ea766nA8sLAa6NcMef0p40HV5eWIzyDixpwNN6uPp97Y1DIR72l2NbXQYEVS2FhZLXYRkAdq2aPlqLV0KukzZ916s07kw+NywrWhfdHEMTkpJl6xBfSn0zGqTRL98qLtWv+0ei1gsXlNFtlPrq9gbuOEjOAaaeWS3G/5MEj1Bea+GDUSnNgE6q4HMjHixoVOV9C0++dU0468PHFQlsi3HvwOJDbUrWfzGPxm/0uJyjrEKmbaJStRI3MI0gZuoh5yZgU4nlFNOHdAiZPD0nDux9YvgXB/m694cMYWh1D6kK76RxIx3Nk+A6uskvTVUnG2ZEj2U+0PYzUvcEV8ovcIO5Fvg6ZgjzTjX7DtocrHE/wdHE83yEaKqmY+dnB50y9A21hpTWG3mdPQ8CxjUbM/60R/CTiGg8Ewqq713AG8FfT6MgFgZQhmEJKH49bozXiN5xW8mjenLnYKkIZsk7jSmw6X28CQn0kZ2rD8+j6xCcqRMEFUlLe58qWs9Krb9ddIBgsp8PEgPgKQrzwOZxXKiod0eMUtGfYXLVIhKdZOHnFf7ucFjwObmqCzjRjxGupVTTEDK4vaw2Lk5BoJVJ5UjUPw8D8aVyCjNWmPCV1wNBE81esPEn6Wds+VkiRNDpWrxJsX2CW/a+ESuuodn2bcnST3pHXO98=
  app: corvo-astral
  on:
    branch: master
