os: linux
language: node_js
node_js:
- '10'
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: nRKlQHBKtDqq8qLJSW9iGEfDXr3nGWCNf7t6qmo3OfkirEl+3/Splj80AXGsZPFEyBlXxVaeDGtfXmgIVffMLjWUj7zhrVnzKnYxe96JjBUwKWfea225RkHpYTsgWcLJd2xsU+P33OqWuN2QzdfgqQtCN9KQlV7vIbftRgLJ8rZ8HGSAm4XA/o8bBLzH8ELZ33l6xL37q8y39wy58cFXWG1SeoG8xpsSEyaz40iy2a47W4RokF961XeAllNA86+Ffo76u9mo8/PXcWVTbnMUmNQ5YTyKISfmmhRL5A4koeOxPhY1ggYUfqYnxI5I4/8urvcVDvsEq0Rd4afF9zQxGDoD23VyLQ5p6u3ddppItom+vR3HGZAN3+MzZmeDHz06r8xOReDGI9O/ITb5wVF8oF+YUBqCs709olCjsY2S1jG3TQht5oIZzo4vUpoM6DZyTm5Y05G0jZe5aUTAHo5XfZ/2O6B7fPMApC0m81Uj4ZyV1YfKbufHEf/pdfvz/sedQRSbirl/cAkAvDFrAt9RPaw6ttdr52m2CsEMnzAR4zoSKFDXmODnhN7i5GVBswOCqgaQOCWub4j6VVAcdPAd8OQNSpKUnzF8vT7nburVuuzGV/JLf1dsj8Ahtjz+KfMoBfbSn2fEu9c4rXFKPUg83uUC/qRh5iom4eEu9Irqrk8=
  app: corvo-astral
  on:
    branch: master
